[build-system]
requires = [
    "hatchling>=1.8.1",
    "jupyterlab~=3.0",
    "jupyter_core",
]
build-backend = "hatchling.build"

[project]
name = "voila"
description = "VoilÃ  turns Jupyter notebooks into standalone web applications"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "Voila Development Team" },
]
keywords = [
    "Jupyter",
    "JupyterLab",
    "Voila",
]
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 3",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "jupyter_client>=6.1.3,<8",
    "jupyter_core>=4.11.0",
    "jupyter_server>=1.18,<2.0.0",
    "jupyterlab_server>=2.3.0,<3",
    "nbclient>=0.4.0,<0.6",
    "nbconvert>=6.4.5,<7",
    "traitlets>=5.0.3,<6",
    "websockets>=9.0",
]
dynamic = [
    "version",
]

[project.license]
file = "LICENSE"

[project.optional-dependencies]
dev = [
    "black",
    "bump2version",
    "jupyter_releaser~=0.6",
]
test = [
    "ipywidgets",
    "matplotlib",
    "mock",
    "numpy",
    "pandas",
    "papermill",
    "pytest",
    "pytest-rerunfailures",
    "pytest-tornasync",
]

[project.scripts]
voila = "voila.app:main"

[project.urls]
Homepage = "https://github.com/voila-dashboards/voila"

[tool.hatch.version]
path = "voila/_version.py"
source = "code"

[tool.hatch.build]
artifacts = [
    "voila/labextension",
]

[tool.hatch.build.targets.wheel.shared-data]
"etc/jupyter/jupyter_server_config.d" = "etc/jupyter/jupyter_server_config.d"
"etc/jupyter/jupyter_notebook_config.d" = "etc/jupyter/jupyter_notebook_config.d"
"etc/jupyter/nbconfig/notebook.d" = "etc/jupyter/nbconfig/notebook.d"
"voila/static" = "share/jupyter/nbextensions/voila"
"voila/labextension/static" = "share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/static"
"install.json" = "share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/install.json"
"voila/labextension/package.json" = "share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/package.json"
"voila/labextension/schemas/@voila-dashboards/jupyterlab-preview" = "share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/schemas/@voila-dashboards/jupyterlab-preview"
"share/jupyter/voila/templates/base/static/07173fb77d2ee655811499d40c8388e7.woff" = "share/jupyter/voila/templates/base/static/07173fb77d2ee655811499d40c8388e7.woff"
"share/jupyter/voila/templates/base/static/07281897a98a61c3733e1670f82a9fd5.woff" = "share/jupyter/voila/templates/base/static/07281897a98a61c3733e1670f82a9fd5.woff"
"share/jupyter/voila/templates/base/static/1.voila.js" = "share/jupyter/voila/templates/base/static/1.voila.js"
"share/jupyter/voila/templates/base/static/2.voila.js" = "share/jupyter/voila/templates/base/static/2.voila.js"
"share/jupyter/voila/templates/base/static/3d580bd561716bfb1f0b4fdd7063a802.woff" = "share/jupyter/voila/templates/base/static/3d580bd561716bfb1f0b4fdd7063a802.woff"
"share/jupyter/voila/templates/base/static/4c74e33b0feb1fdbda49403a5e7ed604.woff" = "share/jupyter/voila/templates/base/static/4c74e33b0feb1fdbda49403a5e7ed604.woff"
"share/jupyter/voila/templates/base/static/5589d1a8fc62be6613020ef2fa13e410.woff" = "share/jupyter/voila/templates/base/static/5589d1a8fc62be6613020ef2fa13e410.woff"
"share/jupyter/voila/templates/base/static/72815766b08ca24d4d29ad1f5d4ecb45.woff" = "share/jupyter/voila/templates/base/static/72815766b08ca24d4d29ad1f5d4ecb45.woff"
"share/jupyter/voila/templates/base/static/77dbcee3c3d9a82a0c04a4ae7992b895.woff" = "share/jupyter/voila/templates/base/static/77dbcee3c3d9a82a0c04a4ae7992b895.woff"
"share/jupyter/voila/templates/base/static/7e83626ba8bf2d20dc41565f1e6d0afc.woff" = "share/jupyter/voila/templates/base/static/7e83626ba8bf2d20dc41565f1e6d0afc.woff"
"share/jupyter/voila/templates/base/static/9995de4787f908d8237dba7007f6c3fe.woff" = "share/jupyter/voila/templates/base/static/9995de4787f908d8237dba7007f6c3fe.woff"
"share/jupyter/voila/templates/base/static/b80e08d5a79acbd1fafb1ca6f3515664.woff" = "share/jupyter/voila/templates/base/static/b80e08d5a79acbd1fafb1ca6f3515664.woff"
"share/jupyter/voila/templates/base/static/bc3af04f9a671fcabd6498042c57478f.woff" = "share/jupyter/voila/templates/base/static/bc3af04f9a671fcabd6498042c57478f.woff"
"share/jupyter/voila/templates/base/static/bc42125861bd5bfc8686deeb612dcbb3.woff" = "share/jupyter/voila/templates/base/static/bc42125861bd5bfc8686deeb612dcbb3.woff"
"share/jupyter/voila/templates/base/static/c9423d5dc9d82a38ca215f74e9cdd9f2.woff" = "share/jupyter/voila/templates/base/static/c9423d5dc9d82a38ca215f74e9cdd9f2.woff"
"share/jupyter/voila/templates/base/static/main.js" = "share/jupyter/voila/templates/base/static/main.js"
"share/jupyter/voila/templates/base/static/require.min.js" = "share/jupyter/voila/templates/base/static/require.min.js"
"share/jupyter/voila/templates/base/static/voila.js" = "share/jupyter/voila/templates/base/static/voila.js"
"share/jupyter/voila/templates/classic/static" = "share/jupyter/voila/templates/classic/static"
"share/jupyter/voila/templates/base/404.html" = "share/jupyter/voila/templates/base/404.html"
"share/jupyter/voila/templates/base/browser-open.html" = "share/jupyter/voila/templates/base/browser-open.html"
"share/jupyter/voila/templates/base/error.html" = "share/jupyter/voila/templates/base/error.html"
"share/jupyter/voila/templates/base/jupyter_widgets.html.j2" = "share/jupyter/voila/templates/base/jupyter_widgets.html.j2"
"share/jupyter/voila/templates/base/log.macro.html.j2" = "share/jupyter/voila/templates/base/log.macro.html.j2"
"share/jupyter/voila/templates/base/page.html" = "share/jupyter/voila/templates/base/page.html"
"share/jupyter/voila/templates/base/spinner.macro.html.j2" = "share/jupyter/voila/templates/base/spinner.macro.html.j2"
"share/jupyter/voila/templates/base/tree.html" = "share/jupyter/voila/templates/base/tree.html"
"share/jupyter/voila/templates/base/voila_setup.macro.html.j2" = "share/jupyter/voila/templates/base/voila_setup.macro.html.j2"
"share/jupyter/voila/templates/reveal/static" = "share/jupyter/voila/templates/reveal/static"
"share/jupyter/voila/templates/lab" = "share/jupyter/voila/templates/lab"
"share/jupyter/voila/templates/classic/index.html.j2" = "share/jupyter/voila/templates/classic/index.html.j2"
"share/jupyter/voila/templates/reveal/index.html.j2" = "share/jupyter/voila/templates/reveal/index.html.j2"

[tool.hatch.build.targets.sdist]
exclude = [
    ".github",
]

[tool.hatch.build.hooks.jupyter-builder]
dependencies = [
    "hatch-jupyter-builder>=0.5.3",
]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "voila/labextension/static/style.js",
]
skip-if-exists = [
    "voila/labextension/static/style.js",
]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "build"
npm = [
    "jlpm",
]
force = true

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = [
    "jlpm",
]

[tool.jupyter-releaser]
skip = [
    "check-links",
]

[tool.jupyter-releaser.hooks]
before-bump-version = [
    "python -m pip install bump2version jupyterlab~=3.0",
]
before-build-npm = [
    "python -m pip install jupyterlab~=3.0",
    "jlpm clean",
    "jlpm build:prod",
]
before-build-python = [
    "jlpm clean",
]
after-draft-release = "bash ./scripts/reset-stable.sh"

[tool.jupyter-releaser.options]
version-cmd = "python scripts/bump-version.py --force"

[tool.tbump]
field = [
    { name = "channel", default = "" },
    { name = "release", default = "" },
]

[tool.tbump.version]
current = "0.3.6"
regex = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)((?P<channel>a|b|rc|.dev)(?P<release>\\d+))?"

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "pyproject.toml"
version_template = "version = \"{major}.{minor}.{patch}{channel}{release}\""

[[tool.tbump.file]]
src = "voila/_version.py"

[license]
file = "LICENSE"
